-- ============================================================
-- Arreglos para el Portafolio (ejecutar en el SQL Editor de Supabase)
-- ============================================================

-- 1) Columna cv_url en la tabla perfil (necesaria para el botón "Descargar CV")
ALTER TABLE perfil ADD COLUMN IF NOT EXISTS cv_url text;

-- 2) Tabla testimonios (panel admin: pestaña Testimonios)
CREATE TABLE IF NOT EXISTS testimonios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text,
  texto text,
  rol text,
  avatar_url text,
  created_at timestamptz DEFAULT now()
);

-- 3) Tabla certificaciones (panel admin: pestaña Certificaciones)
CREATE TABLE IF NOT EXISTS certificaciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text,
  emisor text,
  anio text,
  icono text,
  created_at timestamptz DEFAULT now()
);

-- 4) La seguridad (RLS) ahora se configura con supabase/schema-seguro.sql.
--    No desactives RLS: la clave publicable es visible en el navegador.
