-- ============================================================
-- Seguridad del portafolio (ejecutar en el SQL Editor de Supabase)
-- Lectura pública; escritura solo para usuarios con sesión iniciada.
-- ANTES: en Authentication > Sign In / Providers > Email, desactiva
-- "Allow new users to sign up" para que solo exista tu usuario.
-- ============================================================

CREATE TABLE IF NOT EXISTS mensajes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  correo text NOT NULL,
  mensaje text NOT NULL,
  created_at timestamptz DEFAULT now()
);

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['perfil','proyectos','habilidades','sobre_mi','testimonios','certificaciones']
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS lectura_publica ON %I', t);
    EXECUTE format('DROP POLICY IF EXISTS escritura_admin ON %I', t);
    EXECUTE format('CREATE POLICY lectura_publica ON %I FOR SELECT TO anon, authenticated USING (true)', t);
    EXECUTE format('CREATE POLICY escritura_admin ON %I FOR ALL TO authenticated USING (true) WITH CHECK (true)', t);
  END LOOP;
END $$;

ALTER TABLE mensajes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS enviar_mensaje ON mensajes;
DROP POLICY IF EXISTS admin_mensajes ON mensajes;
CREATE POLICY enviar_mensaje ON mensajes FOR INSERT TO anon, authenticated
  WITH CHECK (char_length(nombre) BETWEEN 1 AND 100 AND char_length(correo) BETWEEN 3 AND 200 AND char_length(mensaje) BETWEEN 1 AND 2000);
CREATE POLICY admin_mensajes ON mensajes FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS img_lectura ON storage.objects;
DROP POLICY IF EXISTS img_admin ON storage.objects;
CREATE POLICY img_lectura ON storage.objects FOR SELECT TO anon, authenticated USING (bucket_id = 'proyectos-imagenes');
CREATE POLICY img_admin ON storage.objects FOR ALL TO authenticated
  USING (bucket_id = 'proyectos-imagenes') WITH CHECK (bucket_id = 'proyectos-imagenes');
